version: '3.5'

services:
  web: 
    image: bref/fpm-dev-gateway
    ports: 
       - '8100:80'
    volumes:
      - ./app:/var/task
    depends_on:
      - php
      - db
    environment: 
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
  php:
    build: 
      context: . 
      dockerfile: ./php/Dockerfile
    environment:
      APP_ENV: dev
      HOTEL_DATABASE_HOST: db
      HOTEL_DATABASE_PORT: 3306
      HOTEL_DATABASE_NAME: hotel_db
      HOTEL_DATABASE_USER: root
      HOTEL_DATABASE_PASSWORD: hotel2be
    volumes:
      - ./app:/var/task
      - ./var:/var/task/var
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: hotel2be
      MYSQL_DATABASE: hotel_db
    ports:
      - "3308:3306"
    volumes:
        - mysql_hotel:/var/lib/mysql 
volumes:
  mysql_hotel:
