
FROM bref/php-82-fpm-dev


# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#install symfoy 
#RUN curl -sS https://get.symfony.com/cli/installer | php  -- --install-dir=/usr/local/bin --filename=symfony