<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5cvrHac\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5cvrHac/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5cvrHac.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5cvrHac\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5cvrHac\App_KernelDevDebugContainer([
    'container.build_hash' => '5cvrHac',
    'container.build_id' => '78d4985d',
    'container.build_time' => 1675304111,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5cvrHac');
