name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Build the Docker image
      run: docker-compose build

    - name: up mysql and apache container runs
      run: docker-compose up -d
  
    - name: Test ./exec command 
      run: ./exec 'php bin/console -V'

    - name: Migration tables
      run: ./exec 'bin/console doctrine:migrations:migrate'

    - name: Load test data
      run: ./exec 'bin/console doctrine:fixtures:load'

    - name: Execute the php unit
      run: ./exec 'bin/phpunit'
